spring.datasource.url=jdbc:postgresql://localhost:5432/stt_project
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

deepgram.api.key=6b50ac55a92274d29698e4eceeb66a62d22f7862
cloudinary.cloud_name=dtpbdk4ji
cloudinary.api_key=873791929376836
cloudinary.api_secret=nnw882v8BvffpGrtMCGCrDgxc3A